version: '2'

networks:
  xwiki-bridge:
    driver: bridge
services:
  postgresql:
    image: postgres:16.0
    container_name: xwiki-pgsql
    environment:
      POSTGRES_USER: xwikidb
      POSTGRES_PASSWORD: xwikipwd
      POSTGRES_DB: xwiki
    networks:
      - xwiki-bridge
    stdin_open: true
    tty: true
    restart: unless-stopped
  xwiki-tomcat:
    build: ../
    image: zwindler/xwiki-tomcat9:latest
    container_name: xwiki-app
    depends_on:
      - postgresql
    environment:
      POSTGRES_INSTANCE: xwiki-pgsql
      POSTGRES_USER: xwikidb
      POSTGRES_PASSWORD: xwikipwd
      POSTGRES_DB: xwiki
    ports:
     - "8080:8080"
    networks:
      - xwiki-bridge
    restart: unless-stopped
